name: Clone Repositories

on:
  workflow_dispatch:

jobs:
  clone-repositories:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Read repository URL from file
        id: read-url
        run: |
          repo_url=$(cat repos.txt)
          echo "REPO_URL=$repo_url" >> $GITHUB_ENV
      - name: Clone repo into tools folder
        run: |
          mkdir -p tools
          git clone $REPO_URL tools/
      - name: Commit and push changes
        run: |
          git config --global user.name "AyudaEnPython[bot]"
          git config --global user.email "<>"
          git add tools/
          git commit -m "Add cloned repository to tools"
          git push origin main
