name: Generate page
on:
  push:
    paths:
      - "data/data.csv"
      - "templates/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate data.json
        run: python utils.py
      - name: Generate index.html
        run: python main.py
      - name: Commit changes
        run: |
          git config user.name "AyudaEnPython[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/data.json index.html
          git commit -m "Automated update of data.json and index.html" || echo "No changes to commit"
      - name: Push changes
        run: git push origin main
