name: Build and Deploy

on:
  push:
    paths:
      - "data/data.csv"
      - "templates/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate data.json
        run: |
          source .venv/bin/activate
          python utils.py

      - name: Generate index.html
        run: |
          source .venv/bin/activate
          python main.py

      - name: Commit changes
        run: |
          git config user.name "AyudaEnPython[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/data.json index.html
          git commit -m "Automated update of data.json and index.html" || echo "No changes to commit"
